name: Lint

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check format
        run: pip install black; black --check .
